name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: L01
      id: l01
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: L01
        setup-command: ''
        command: make -s L_01
        timeout: 1
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        L01_RESULTS: "${{steps.l01.outputs.result}}"
      with:
        runners: l01
